export const PAGES = [
  ['asset', 'Asset'],
  ['asset-express', 'Asset Express'],
  ['asset-mongo', 'Asset-Mongo'],
  ['asset-s3', 'Asset-S3'],
  ['auth', 'Auth'],
  ['base', 'Base'],
  ['cache', 'Cache'],
  ['compiler', 'Compiler'],
  ['config', 'Config '],
  ['context', 'Context'],
  ['di', 'DI (Dependency Injection)'],
  ['email', 'Email'],
  ['exec', 'Exec'],
  ['express', 'Express'],
  ['log', 'Log'],
  ['model', 'Model'],
  ['model-elasticsearch', 'Elasticsearch'],
  ['model-mongo', 'Mongo'],
  ['pool', 'Pool'],
  ['registry', 'Registry'],
  ['schedule', 'Schedule '],
  ['schema', 'Schema'],
  ['starter', 'Starter'],
  ['test', 'Test'],
  ['util', 'Util'],
];
